version: '3'

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=miot
      - POSTGRES_PASSWORD=1234abcd
      - POSTGRES_DB=miot