spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miot?allowMultiQueries=true
    username: miot
    password: 1234abcd
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    placeholder-replacement: false